apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-project2
  namespace: argocd
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: project1
  source:
    path: apps/project2
    repoURL: https://github.com/sergioarmgpl/IDPKCDColombia2023
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true