apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-project1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: project1
  source:
    path: apps/project1
    repoURL: https://github.com/sergioarmgpl/IDPKCDColombia2023
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true