apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: project1
  source:
    path: templates/template1
    repoURL: https://github.com/sergioarmgpl/IDPKCDColombia2023
    targetRevision: HEAD
    helm:
      values: |
        appname: app1
        dockerImage: czdev/myapp
        namespace: development
        message: "jose"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
